### ISSUE TITLE
UI / UX NOT INTUITIVE

### ISSUE THREAD

**Issue by hilz0r** [CrossMark/foosbam#24]
Dear reader,

![image](https://github.com/CrossMark/foosbam/assets/153621338/f0350b65-6b4c-4368-a8a5-cfc363e0d9fc)

there is too much whitespace between the button and the actual score. if you click the button now the number falls of your eyes, this makes stuff looks buggy. please put the buttons and the score next to each other

Thanks in advance!!
Kind regards,
A happy customer

**Comment by CrossMark** [comment]
Duplicate for https://github.com/CrossMark/foosbam/issues/21
