### ISSUE TITLE
New season

### ISSUE THREAD

**Issue by Robin-vlap-vlap** [CrossMark/foosbam#45]
- Reset scores back 1500
- Hide inactive players - Inactive means less then 5 games played in season 
- Make final score of season 1 --> save on history page (to be build) drop down with all time score and season score.
- Automate every quarter

**Comment by CrossMark** [comment]
**Columns to add**
- [x] Add `season` column to `matches`
- [x] Add `season` column to `ratings`
- [x] Add `rating_season` column to `ratings`
- [x] Add `previous_rating_season` column to `ratings`

**ELO functions**
1. Check if rating for the season the match is played in already exists.
2. If no rating exists:
    - `rating_season = 1500`
    - `previous_rating_season = NULL`
3. If rating exists:
    - Calculate new rating
        - K-factor for ratings should be based on all games played
    - Add new rating to `rating_season`

**Ranking page**
- [ ] Create function to fill drop down with only the seasons thus far, also add _All time_
- [ ] Create drop down with seasons (also include from/to date)
- [ ] On default show ranking of current season
- [ ] Only show players with a minimal of 5 games in that season

**Comment by CrossMark** [comment]
**Post-deploy**

- [ ] Fill `season` column in `matches` and `ratings`
- [ ] Change `nullable=True` to `nullable=False, default = -1` in the models
